image: node:22

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script: []

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'

stages: 
  - test

secret_detection:
  before_script: []

semgrep-sast:
  before_script: []

gitlab-advanced-sast:
  before_script: []

# Given the small size of the project this is fine to do
clawpass:
  stage: test
  script:
    - cd skills/clawpass
    - npm ci --cache ../../.npm --prefer-offline --legacy-peer-deps
    - npm run build
    - npm run test
    - npm audit --omit=dev --audit-level=low
  artifacts:
    paths:
      - skills/clawpass/scripts/
    expire_in: 1 day
  rules:
    - changes:
        - skills/clawpass/**/*
